import { communityRequest } from './community-transport.js';

const $ = selector => document.querySelector(selector);
const el = (tag,className,text) => { const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node; };
const token=localStorage.getItem('sweetfrog-session')||'';
const request=(path,options={})=>communityRequest(path,options,token);
const sections={overview:'总览',suggestions:'意见留言',topics:'玩家社区',leaderboards:'排行榜',users:'玩家账号'};
const games={tap:'逮住大青蛙',merge:'合成大青蛙',flap:'青蛙起飞',puzzle:'青蛙2048',aim:'青蛙定位练习'};
let section='overview',game='tap';
function button(label,click,className=''){const node=el('button',className,label);node.type='button';node.addEventListener('click',click);return node;}
function status(message){$('#admin-status').textContent=message;}
function empty(message){return el('p','admin-empty',message);}
async function remove(path,label){if(!confirm(`确定删除${label}？此操作无法撤销。`))return;try{await request(path,{method:'DELETE'});status(`已删除${label}`);await render();}catch(error){status(error.message);}}
function card(title,meta,body,action){const node=el('article','admin-card');const top=el('div','admin-card-top');top.append(el('h3','',title),el('span','',meta));node.append(top,el('p','',body));if(action)node.append(action);return node;}
async function overview(content){const data=await request('/api/admin/overview');const grid=el('div','admin-metrics');for(const [key,label] of [['users','玩家'],['suggestions','提议'],['topics','话题'],['replies','回复'],['scores','榜单成绩']]){const item=el('div','admin-metric');item.append(el('strong','',String(data[key])),el('span','',label));grid.append(item);}content.append(grid,empty('使用上方栏目查看和管理具体内容。'));}
async function suggestions(content){const data=await request('/api/admin/suggestions');if(!data.items.length){content.append(empty('暂无提议。'));return;}for(const item of data.items)content.append(card(item.title,`${item.username} · ${item.votes} 赞`,item.body,button('删除提议',()=>remove(`/api/admin/suggestions/${item.id}`,`提议“${item.title}”`),'admin-danger')));}
async function topics(content){const data=await request('/api/admin/topics');if(!data.items.length){content.append(empty('暂无话题。'));return;}for(const item of data.items){const entry=card(item.title,`${item.username} · ${item.replyCount} 条回复`,item.body,button('删除话题',()=>remove(`/api/admin/topics/${item.id}`,`话题“${item.title}”`),'admin-danger'));const replies=el('div','admin-replies');entry.append(button('查看回复',async()=>{if(replies.childElementCount){replies.replaceChildren();return;}replies.append(empty('正在加载回复…'));try{const data=await request(`/api/topics/${item.id}/replies`);replies.replaceChildren();if(!data.items.length)replies.append(empty('暂无回复。'));for(const reply of data.items){const row=el('div','admin-reply');row.append(el('strong','',reply.username),el('p','',reply.body),button('删除回复',()=>remove(`/api/admin/replies/${reply.id}`,`回复 #${reply.id}`),'admin-danger'));replies.append(row);}}catch(error){replies.replaceChildren(empty(error.message));}},'admin-secondary'),replies);content.append(entry);}}
async function leaderboards(content){const tabs=el('div','admin-game-tabs');for(const [key,label] of Object.entries(games)){const tab=button(label,()=>{game=key;render();},'admin-secondary');tab.classList.toggle('selected',key===game);tabs.append(tab);}content.append(tabs);const data=await request(`/api/admin/leaderboards/${game}`);if(!data.items.length){content.append(empty('这款游戏还没有上榜成绩。'));return;}for(const [index,item] of data.items.entries()){const row=el('div','admin-score-row');row.append(el('span','',`#${index+1}`),el('strong','',item.username),el('span','',`${item.score} 分`),button('移除成绩',()=>remove(`/api/admin/leaderboards/${game}/${item.userId}`,`${item.username} 的成绩`),'admin-danger'));content.append(row);}}
async function users(content){const data=await request('/api/admin/users');if(!data.items.length){content.append(empty('暂无玩家。'));return;}for(const item of data.items){const row=el('div','admin-score-row');row.append(el('strong','',item.username),el('span','',item.role==='admin'?'管理员':item.banned?'已停用':'玩家'),el('span','',item.createdAt));if(item.role!=='admin')row.append(button(item.banned?'恢复账号':'停用账号',async()=>{const action=item.banned?'恢复':'停用';if(!confirm(`确定${action}玩家 ${item.username} 的账号？`))return;try{await request(`/api/admin/users/${item.id}/ban`,{method:'POST',body:JSON.stringify({banned:!item.banned})});status(`已${action}账号`);await render();}catch(error){status(error.message);}},item.banned?'admin-secondary':'admin-danger'));content.append(row);}}
async function render(){const tabs=$('#admin-tabs'),content=$('#admin-content');tabs.replaceChildren();for(const [key,label] of Object.entries(sections)){const tab=button(label,()=>{section=key;render();},'admin-tab');tab.classList.toggle('selected',key===section);tabs.append(tab);}content.replaceChildren(empty('正在加载…'));try{const next=el('div','admin-list');await({overview,suggestions,topics,leaderboards,users})[section](next);content.replaceChildren(next);status('');}catch(error){content.replaceChildren(empty(error.message));status(error.message);}}
$('#admin-refresh').addEventListener('click',render);
try{const data=await request('/api/session');if(!data.user){status('请先登录管理员账号。');const link=el('a','admin-login','前往登录 ↗');link.href='./index.html#account';$('#admin-status').after(link);}else if(data.user.role!=='admin'){status('当前账号没有管理员权限。');}else{$('#admin-app').hidden=false;$('#admin-user').textContent=`管理员：${data.user.username}`;await render();}}catch(error){status(error.message);}
