import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
const base = process.env.COMMUNITY_TEST_URL || 'http://127.0.0.1:4175/';
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 850 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '#suggestions');
  await page.locator('.club-heading h1').getByText('意见留言').waitFor();
  assert.match(await page.locator('.club-gate').textContent(), /登录后可以发布建议/);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.match(await page.locator('#sound-toggle').textContent(),/声音开/);
  await page.locator('#sound-toggle').click();
  assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'),'false');
  await page.locator('#sound-toggle').click();
  assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'),'true');
  await page.goto(base + '#account');
  await page.getByRole('button', { name: '注册', exact: true }).click();
  const username = 'frog' + Math.floor(Math.random() * 100000000);
  await page.locator('[name=username]').fill(username);
  await page.locator('[name=password]').fill('testpassword123');
  await page.getByRole('button', { name: '创建账号 ↗' }).click();
  await page.waitForURL('**/#games');
  assert.equal(await page.locator('.site-header nav a.club-nav-link[href="#account"]').count(),0);
  assert.match(await page.locator('#account-chip').textContent(),/ID \d+/);
  await page.locator('#account-chip').click();
  await page.waitForURL('**/#profile');
  assert.match(await page.locator('.profile-facts').textContent(),/玩家 ID/);
  const renamed=username+'x';
  await page.locator('.profile-panel').first().locator('[name=username]').fill(renamed);
  await page.locator('.profile-panel').first().locator('[name=currentPassword]').fill('wrong');
  await page.getByRole('button',{name:'保存用户名'}).click();
  await page.getByText('当前密码不正确').waitFor();
  await page.locator('.profile-panel').first().locator('[name=currentPassword]').fill('testpassword123');
  await page.getByRole('button',{name:'保存用户名'}).click();
  await page.getByText('用户名已更新。').waitFor();
  assert.match(await page.locator('#account-chip').textContent(),new RegExp(renamed));
  const dataUrl=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=200;const x=c.getContext('2d');x.fillStyle='#ed7c74';x.fillRect(0,0,200,200);return c.toDataURL('image/png');});
  await page.locator('.profile-avatar-form input[type=file]').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:Buffer.from(dataUrl.split(',')[1],'base64')});
  await page.getByRole('button',{name:'保存头像'}).click();
  await page.getByText('头像已更新。').waitFor();
  const playerId=Number((await page.locator('#account-chip').textContent()).match(/ID (\d+)/)[1]);
  assert.match((await page.request.get(base+`api/avatars/${playerId}`)).headers()['content-type'],/image\/webp|image\/jpeg/);
  await page.goto(base + '#suggestions');
  const suggestionTitle = '测试提议' + username;
  await page.locator('.club-form [name=title]').fill(suggestionTitle);
  await page.locator('.club-form [name=body]').fill('可以加一个倒计时提示。');
  await page.getByRole('button', { name: '发布建议 ↗' }).click();
  await page.waitForURL('**/#suggestions/*');
  await page.getByRole('heading', { name: suggestionTitle }).waitFor();
  assert.match(await page.locator('.forum-detail .club-avatar').getAttribute('src'),new RegExp(`/api/avatars/${playerId}`));
  await page.locator('.forum-detail .vote-button').click();
  await page.locator('.forum-detail .vote-button').getByText('1').waitFor();
  assert.match(await page.locator('.forum-detail .vote-button').textContent(), /1/);
  await page.getByRole('link', { name: '返回建议列表' }).click();
  await page.locator('.idea-card .forum-title').filter({ hasText: suggestionTitle }).click();
  await page.getByRole('heading', { name: suggestionTitle }).waitFor();
  await page.goto(base + '#discussion');
  const topicTitle = '测试话题' + username;
  await page.locator('.club-form [name=title]').fill(topicTitle);
  await page.locator('.club-form [name=body]').fill('大家最喜欢哪个游戏？');
  await page.getByRole('button', { name: '发布帖子 ↗' }).click();
  await page.waitForURL('**/#discussion/*');
  await page.getByRole('heading', { name: topicTitle }).waitFor();
  await page.locator('.club-reply-form textarea').fill('我喜欢青蛙2048。');
  await page.getByRole('button', { name: '发送回复' }).click();
  await page.getByText('我喜欢青蛙2048。').waitFor();
  await page.getByRole('link', { name: '返回帖子列表' }).click();
  await page.locator('.topic-card .forum-title').filter({ hasText: topicTitle }).click();
  await page.getByText('我喜欢青蛙2048。').waitFor();
  await page.goto(base + '#leaderboard');
  assert.equal(await page.locator('.club-tab').count(), 5);
  await page.goto(base + '#profile');
  await page.getByRole('button',{name:'恢复默认头像'}).click();
  await page.getByText('已恢复默认头像。').waitFor();
  assert.match((await page.request.get(base+`api/avatars/${playerId}`)).headers()['content-type'],/image\/svg\+xml/);
  await page.locator('.profile-panel').nth(1).locator('[name=currentPassword]').fill('testpassword123');
  await page.locator('.profile-panel').nth(1).locator('[name=newPassword]').fill('changedPassword456!');
  await page.locator('.profile-panel').nth(1).locator('[name=confirmPassword]').fill('mismatchPassword456!');
  await page.getByRole('button',{name:'更新密码'}).click();
  await page.getByText('两次输入的新密码不一致。').waitFor();
  await page.locator('.profile-panel').nth(1).locator('[name=confirmPassword]').fill('changedPassword456!');
  await page.getByRole('button',{name:'更新密码'}).click();
  await page.waitForURL('**/#account');
  await page.getByText('密码已更新，请用新密码重新登录。').waitFor();
  await page.locator('[name=username]').fill(renamed);
  await page.locator('[name=password]').fill('changedPassword456!');
  await page.getByRole('button',{name:'登录 ↗'}).click();
  await page.waitForURL('**/#games');
  await page.locator('#account-chip').click();
  await page.getByRole('button', { name: '退出登录' }).click();
  await page.waitForURL('**/#account');
  await page.goto(base + '#leaderboard');
  assert.match(await page.locator('.club-my-rank').textContent(), /游客可以看榜/);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.goto(base + '#discussion');
  await page.locator('.topic-card .forum-title').filter({ hasText: topicTitle }).click();
  await page.getByText('我喜欢青蛙2048。').waitFor();
  assert.match(await page.locator('.forum-replies-section .club-gate').textContent(), /登录后/);
  const desktop=await browser.newPage({ viewport:{width:1280,height:900} });
  await desktop.goto(base+'#discussion');
  await desktop.locator('.forum-list').waitFor();
  assert.equal(await desktop.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await desktop.close();
  assert.deepEqual(errors, []);
  await page.close();
  console.log('PASS: guest browsing, registration, suggestions, unique vote, discussion, reply and responsive leaderboard');
} finally { await browser.close(); }
