import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdtempSync } from 'node:fs';
import { rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const root=resolve(import.meta.dirname,'..'),state=mkdtempSync(join(tmpdir(),'sweetfrog-match-browser-'));
const cli=join(root,'node_modules/wrangler/bin/wrangler.js'),port=44000+Math.floor(Math.random()*10000),base=`http://127.0.0.1:${port}`;
let server,browser;
try{
  execFileSync(process.execPath,[cli,'d1','execute','sweetfrog-db','--local','--persist-to',state,'--file','cloudflare/schema.sql'],{cwd:root,stdio:'pipe'});
  server=spawn(process.execPath,[cli,'pages','dev','dist','--port',String(port),'--persist-to',state],{cwd:root,stdio:['ignore','pipe','pipe']});
  let logs='';server.stdout.on('data',data=>logs+=data);server.stderr.on('data',data=>logs+=data);
  let ready=false;for(let i=0;i<120;i++){try{if((await fetch(base+'/api/presence')).ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,250));}
  assert.ok(ready,logs);
  const register=async prefix=>{const response=await fetch(base+'/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:prefix+Math.floor(Math.random()*100000),password:'password123'})});assert.equal(response.status,200);return response.json();};
  const host=await register('quickhost'),guest=await register('quickguest');
  browser=await chromium.launch({headless:true,channel:'msedge'});
  const hostPage=await browser.newPage({viewport:{width:1280,height:900}}),guestPage=await browser.newPage({viewport:{width:390,height:850}});
  const errors=[];for(const page of [hostPage,guestPage])page.on('pageerror',error=>errors.push(error.message));
  await hostPage.addInitScript(value=>localStorage.setItem('sweetfrog-session',value),host.token);
  await guestPage.addInitScript(value=>localStorage.setItem('sweetfrog-session',value),guest.token);
  await hostPage.goto(base+'/#games');await hostPage.locator('#online-total').waitFor();
  await guestPage.goto(base+'/#games');
  await hostPage.waitForFunction(()=>Number(document.querySelector('#online-total').textContent)>=1);
  await hostPage.locator('#account-chip').hover();
  await hostPage.locator('#account-popover').getByRole('button',{name:'退出登录'}).waitFor({state:'visible'});
  await hostPage.locator('#account-popover').getByRole('link',{name:'个人信息'}).waitFor({state:'visible'});
  await hostPage.screenshot({path:'tests/account-menu-preview.png'});
  await hostPage.locator('header nav a[href="#games"]').hover();
  await hostPage.waitForFunction(()=>getComputedStyle(document.querySelector('header nav a[href="#games"]')).transform!=='none');
  assert.equal(await hostPage.locator('.brand-mark .sf-icon').count(),1);
  assert.equal(await hostPage.locator('header nav a[href="#match"]').count(),1);
  assert.equal(await hostPage.locator('.spark-one .sf-icon').count(),1);
  assert.equal(await hostPage.locator('.note-smile .sf-icon').count(),1);
  await hostPage.screenshot({path:'tests/match-home-preview.png',fullPage:true});
  await hostPage.locator('.lobby-online-link').click();await hostPage.waitForURL('**/#online');
  await hostPage.getByRole('heading',{name:'在线玩家'}).waitFor();
  await hostPage.getByText(guest.user.username).waitFor();
  assert.equal(await hostPage.locator('.online-player-card').count(),2);
  await hostPage.waitForFunction(()=>[...document.querySelectorAll('.online-player-avatar')].every(image=>image.complete&&image.naturalWidth>0));
  await hostPage.screenshot({path:'tests/online-desktop-preview.png',fullPage:true});
  const visitorPage=await browser.newPage();await visitorPage.goto(base+'/#online');
  await visitorPage.waitForFunction(()=>document.querySelector('#online-page-breakdown')?.textContent.includes('游客 1 人'));
  const browsingGuest=await visitorPage.evaluate(()=>localStorage.getItem('sweetfrog-guest-session'));
  assert.match(browsingGuest,/^[a-f0-9]{64}$/);
  await visitorPage.waitForFunction(()=>document.querySelectorAll('.online-player-card').length===3);
  const visitorName=await visitorPage.locator('.online-player-card').filter({hasText:'游客'}).locator('.online-player-detail strong').first().textContent();
  assert.match(visitorName,/^游客\d{5}/);
  const guestAvatar=visitorPage.locator('.online-player-card').filter({hasText:visitorName}).locator('img');
  await visitorPage.waitForFunction(()=>[...document.querySelectorAll('.online-player-avatar')].every(image=>image.complete&&image.naturalWidth>0));
  assert.match(await guestAvatar.getAttribute('src'),/\/api\/avatars\/\d+/);
  assert.match(await visitorPage.evaluate(async src=>(await fetch(src)).url,await guestAvatar.getAttribute('src')),/guest-frog-avatar\.svg$/);
  await visitorPage.close();
  await hostPage.getByRole('button',{name:'刷新名单'}).click();
  await hostPage.getByRole('link',{name:'去快速匹配 →'}).click();await hostPage.waitForURL('**/#match');
  await guestPage.goto(base+'/#online');await guestPage.getByText(host.user.username).waitFor();
  assert.equal(await guestPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.equal(await guestPage.evaluate(()=>{const chip=document.querySelector('.account-chip').getBoundingClientRect();return [...document.querySelectorAll('.site-header nav>a:not(.account-chip)')].some(link=>{const box=link.getBoundingClientRect();return box.left<chip.right&&box.right>chip.left&&box.top<chip.bottom&&box.bottom>chip.top;});}),false,'mobile account chip must not cover navigation links');
  await guestPage.screenshot({path:'tests/online-mobile-preview.png',fullPage:true});
  await guestPage.goto(base+'/#match');
  await guestPage.locator('[data-match-game="tap"]').waitFor();
  await hostPage.locator('[data-match-game="tap"]').click();
  await hostPage.getByRole('button',{name:'匹配「逮住大青蛙」对手 →'}).click();
  await hostPage.locator('#match-searching').waitFor({state:'visible'});
  await guestPage.waitForFunction(()=>Number(document.querySelector('[data-match-game="tap"] .match-mode-waiting strong').textContent)>=1,{timeout:10000});
  await guestPage.screenshot({path:'tests/match-mobile-preview.png',fullPage:true});
  await guestPage.locator('[data-match-game="tap"]').click();
  await guestPage.getByRole('button',{name:'匹配「逮住大青蛙」对手 →'}).click();
  await guestPage.locator('#match-found').waitFor({state:'visible',timeout:10000});
  await hostPage.locator('#match-found').waitFor({state:'visible',timeout:10000});
  assert.equal(await guestPage.locator('#match-modes').isVisible(),false);
  await guestPage.waitForFunction(name=>document.querySelector('.match-duel-opponent strong')?.textContent===name,host.user.username);
  await guestPage.screenshot({path:'tests/match-found-mobile-preview.png',fullPage:true});
  await hostPage.waitForURL('**/#pk/*',{timeout:10000});await guestPage.waitForURL('**/#pk/*',{timeout:10000});
  assert.equal(new URL(hostPage.url()).hash,new URL(guestPage.url()).hash);
  await hostPage.locator('#pk-game').waitFor({state:'visible',timeout:12000});
  await guestPage.locator('#pk-game').waitFor({state:'visible',timeout:12000});
  assert.equal(await guestPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const touristPage=await browser.newPage({viewport:{width:390,height:850}});touristPage.on('pageerror',error=>errors.push(error.message));
  await touristPage.goto(base+'/#match');
  await touristPage.getByRole('button',{name:'匹配「逮住大青蛙」对手 →'}).waitFor({state:'visible'});
  await touristPage.waitForFunction(()=>!document.querySelector('#match-start').disabled);
  const tourist=await touristPage.evaluate(async()=>{const token=localStorage.getItem('sweetfrog-guest-session');const response=await fetch('/api/session',{headers:{Authorization:`Bearer ${token}`}});return (await response.json()).user;});
  assert.match(tourist.username,/^游客\d{5}$/);assert.equal(tourist.role,'guest');
  await touristPage.getByRole('button',{name:'匹配「逮住大青蛙」对手 →'}).click();
  await touristPage.locator('#match-searching').waitFor({state:'visible'});
  await hostPage.goto(base+'/#match');await hostPage.getByRole('button',{name:'匹配「逮住大青蛙」对手 →'}).click();
  await hostPage.locator('#match-found').waitFor({state:'visible',timeout:10000});
  await hostPage.waitForFunction(name=>document.querySelector('.match-duel-opponent strong')?.textContent===name,tourist.username);
  await touristPage.waitForURL('**/#pk/*',{timeout:10000});
  await touristPage.locator('#pk-game').waitFor({state:'visible',timeout:12000});
  assert.equal(await touristPage.locator('.pk-player-name').getByText(tourist.username).count(),1);
  await touristPage.close();
  await hostPage.locator('#account-chip').hover();
  await hostPage.locator('#account-popover').getByRole('button',{name:'退出登录'}).click();
  await hostPage.waitForURL('**/#account');
  assert.equal(await hostPage.locator('#account-chip').getByText('登录').count(),1);
  assert.deepEqual(errors,[]);
  console.log('PASS: signed-in and guest matchmaking, five-digit guest name, shared PK room and mobile layout');
}finally{
  await browser?.close();
  if(server){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill();await stopped;}
  if(state.startsWith(join(tmpdir(),'sweetfrog-match-browser-')))await rm(state,{recursive:true,force:true,maxRetries:10,retryDelay:500});
}
