ALTER TABLE pk_rooms ADD COLUMN game TEXT NOT NULL DEFAULT 'tap';
ALTER TABLE pk_rooms ADD COLUMN host_seq INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pk_rooms ADD COLUMN guest_seq INTEGER NOT NULL DEFAULT 0;
