PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, public_id INTEGER NOT NULL UNIQUE CHECK(public_id BETWEEN 10000 AND 99999), username TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'player', banned INTEGER NOT NULL DEFAULT 0, avatar_data TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS suggestions(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS suggestion_votes(suggestion_id INTEGER NOT NULL REFERENCES suggestions(id), user_id INTEGER NOT NULL REFERENCES users(id), PRIMARY KEY(suggestion_id,user_id));
CREATE TABLE IF NOT EXISTS topics(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS replies(id INTEGER PRIMARY KEY, topic_id INTEGER NOT NULL REFERENCES topics(id), user_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS scores(user_id INTEGER NOT NULL REFERENCES users(id), game TEXT NOT NULL, score INTEGER NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,game));
CREATE TABLE IF NOT EXISTS auth_attempts(ip_hash TEXT PRIMARY KEY, count INTEGER NOT NULL, until INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pk_rooms(code TEXT PRIMARY KEY, host_id INTEGER NOT NULL REFERENCES users(id), guest_id INTEGER REFERENCES users(id), game TEXT NOT NULL DEFAULT 'tap', is_match INTEGER NOT NULL DEFAULT 0, round INTEGER NOT NULL DEFAULT 1, revision INTEGER NOT NULL DEFAULT 0, rematch_by INTEGER, host_ready INTEGER NOT NULL DEFAULT 0, guest_ready INTEGER NOT NULL DEFAULT 0, host_score INTEGER NOT NULL DEFAULT 0, guest_score INTEGER NOT NULL DEFAULT 0, host_seq INTEGER NOT NULL DEFAULT 0, guest_seq INTEGER NOT NULL DEFAULT 0, host_last_hit INTEGER NOT NULL DEFAULT 0, guest_last_hit INTEGER NOT NULL DEFAULT 0, seed INTEGER NOT NULL, starts_at INTEGER, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_pk_rooms_created ON pk_rooms(created_at);
CREATE TABLE IF NOT EXISTS online_presence(client_key TEXT PRIMARY KEY, user_id INTEGER, game TEXT, last_seen INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_online_presence_seen ON online_presence(last_seen);
CREATE TABLE IF NOT EXISTS match_queue(user_id INTEGER PRIMARY KEY REFERENCES users(id), game TEXT NOT NULL, mode TEXT NOT NULL DEFAULT 'fixed', status TEXT NOT NULL DEFAULT 'waiting', joined_at INTEGER NOT NULL, last_seen INTEGER NOT NULL, room_code TEXT);
CREATE INDEX IF NOT EXISTS idx_match_queue_find ON match_queue(game,status,joined_at);
CREATE TABLE IF NOT EXISTS match_results(room_code TEXT NOT NULL, round INTEGER NOT NULL, host_id INTEGER NOT NULL, guest_id INTEGER NOT NULL, winner_id INTEGER, finished_at INTEGER NOT NULL, PRIMARY KEY(room_code,round));
CREATE INDEX IF NOT EXISTS idx_match_results_host ON match_results(host_id);
CREATE INDEX IF NOT EXISTS idx_match_results_guest ON match_results(guest_id);
CREATE INDEX IF NOT EXISTS idx_match_results_winner ON match_results(winner_id);
CREATE TABLE IF NOT EXISTS friend_links(user_low INTEGER NOT NULL REFERENCES users(id), user_high INTEGER NOT NULL REFERENCES users(id), requester_id INTEGER NOT NULL REFERENCES users(id), status TEXT NOT NULL CHECK(status IN ('pending','accepted','declined')), updated_at INTEGER NOT NULL, PRIMARY KEY(user_low,user_high));
CREATE INDEX IF NOT EXISTS idx_friend_links_high ON friend_links(user_high,status);
CREATE TABLE IF NOT EXISTS friend_messages(id INTEGER PRIMARY KEY, sender_id INTEGER NOT NULL REFERENCES users(id), recipient_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at INTEGER NOT NULL, read_at INTEGER);
CREATE INDEX IF NOT EXISTS idx_friend_messages_inbox ON friend_messages(recipient_id,sender_id,id);
CREATE TABLE IF NOT EXISTS pk_invites(id INTEGER PRIMARY KEY, room_code TEXT NOT NULL REFERENCES pk_rooms(code), from_user INTEGER NOT NULL REFERENCES users(id), to_user INTEGER NOT NULL REFERENCES users(id), status TEXT NOT NULL CHECK(status IN ('pending','accepted','declined','expired')), created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_pk_invites_inbox ON pk_invites(to_user,status,created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_pk_invites_pending ON pk_invites(room_code,to_user) WHERE status='pending';
CREATE INDEX IF NOT EXISTS idx_suggestions_created ON suggestions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topics_created ON topics(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scores_game_score ON scores(game,score DESC);
